### PR TITLE
Add Search/Filter Input for Archived Projects

### LINKED ISSUE #277: Add Search/Filter Input for Archived Projects
If you have many archived projects, it gets messy. Let's add a search input to filter the projects by their names.

### PR DESCRIPTION
**Pull request by j0hannesr0th**
Fixes #277

Aufzeichnung-2024-05-23-210230

### CODE REVIEW

**Comment by j0hannesr0th** [comment]
Hi @julien-nc any chance this will be merged soon? Do you want some changes?

**Comment by julien-nc** [comment]
Sorry for the response time and thanks a lot for the PR.
Why not having this filter for both classic and archived projects?
It would be nice to combine it with the project creation button in one line, like in Talk:
image
Wdyt?

**Comment by julien-nc** [comment]
To spare you the burden of rebasing. I made something similar to this PR. It's in the main branch now.
Anyway there is some refactoring going on in the UI these days.

I'm interested to know what you think about the current implementation and UX of the project filter.
I also added bill filtering.

**Comment by j0hannesr0th** [comment]
Hi @julien-nc sorry for late response. I'm fine with your solution. 👍🏻

**Pull request closed without merging**
